language: php

services: mongodb

php:
  - 5.6
  - 7.0
  - 7.1

before_script:
  - echo 'extension=mongodb.so' >> ~/.phpenv/versions/$(phpenv version-name)/etc/php.ini
  - echo 'extension=mongo.so' >> ~/.phpenv/versions/$(phpenv version-name)/etc/php.ini
  - composer --prefer-source install

script: phpunit --coverage-text --verbose
